language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed mohamedatef25/udagram-api-feed
  - docker tag udagram-api-user mohamedatef25/udagram-api-user
  - docker tag reverseproxy mohamedatef25/reverseproxy
  - docker tag udagram-frontend mohamedatef25/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mohamedatef25/udagram-api-feed:v1
  - docker push mohamedatef25/udagram-api-user:v1
  - docker push mohamedatef25/reverseproxy:v1
  - docker push mohamedatef25/udagram-frontend:v1