apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: ASIAQF7IAB4ERBTOFQZK
  aws_secret_access_key: Wj+nB2b4UZznWkNXgxjONZQStJGBYv8SDpiB+487
  aws_session_token: FwoGZXIvYXdzEAQaDBVam1KFWT/n0w1p2SK8AcrTJ/usUT6veMPeLhSaC9U+JS+4CFY5tFp08vGhWW0p0ZHcCpEwDAoJtPAqGSDqtphvtNKeNV39jpKBTIZzV8RrLaiZ7IRT4z9ToqMvTnM/4VVhDuogsg+IRFAXo8Ed7XvdlB36VvJkbtYHIqLHoHc6ZL5nHQs9brsgXKAmm/K75haHgG35wgLnRdzGHMJ+gVXNNffHICRI63ddLH6iGQ8JE+PBlvsddZA+0Xxmp1Vd/N/GYHNwKXKZhPP3KMHU7JkGMi1ESK09d+ZRG2YOYouFQLhTkRYDTcdNsM+DPkkDrb2DbrceTpCCzdlzSGGNtLo=